### ISSUE TITLE
Data is unavailable

### ISSUE THREAD

**Issue by ZJU-PLP** [esteng/guiding-multi-step#2]
@andyzeng 
Dear andy:

The data link is unavailable when I want to download. Would you mind updating it ?

**Comment by esteng** [comment]
I just checked the data link and it seems to be working -- are you sure that you've opened the issue in the correct repo? (Andy wasn't on this paper)

**Comment by ZJU-PLP** [comment]
> I just checked the data link and it seems to be working -- are you sure that you've opened the issue in the correct repo? (Andy wasn't on this paper)

Thanks for your quick reply.
I am sorry and wrong to @author. The link cannot be opened in chrome while can be opened in Firefox.
